name: build,test and deploy jobs
on: push
jobs: 
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: download repo
        uses: actions/checkout@v4

      - name: add to file
        run: echo "hi bro whats up" >> hello.txt

      - name: upload file 
        uses: actions/upload-artifact@v7
        with:
          name: hello file artifact
          path: hello.txt

      - name: present working directory
        run: pwd

  test_job:
    needs: build_job
    runs-on: ubuntu-latest
    steps:
      - name: Download file 
        uses: actions/download-artifact@v8
        with:
          name: hello filesss artifact
         

      - name: read the files
        run: cat hello.txt

  deploy_job:
    needs: build_job
    runs-on: ubuntu-latest
    steps:
      
      - name: Download file 
        uses: actions/download-artifact@v8
        with:
          name: hello file artifact
      
      - name: search for a string in hello file
        run: grep -i "bro" hello.txt

      - name: deploy the job to k8
        run: echo "Job is succusefully deployed with new version app16"
